services:
  front-end-mfe:
    container_name: front-end-mfe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    restart: always
    environment:
      - JWT_SECRET=secret123
      - REACT_API_URL=http://172.24.48.1:3001
